from download.sources.direct_source import DirectSource
from download.sources.enginehub_source import EnginehubSource
from download.sources.spigotmc_source import SpigotmcSource
from download.sources.jenkins_source import JenkinsSource
from download.sources.modrinth_source import ModrinthSource
from download.sources.github_source import GithubSource
from download.sources.papermc_source import PapermcSource
from download.sources.zrips_source import ZripsSource
from download.sources.fabricmc_source import FabricmcSource